name: Deploy to GitHub Pages
# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
jobs:
  deploy-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Edit a .NET Core database connection string in appsettings.json
      uses: benday-inc/edit-dbconnstr-in-appsettings@v1.3
      with:
        pathToSettingsFile: ./KittyPics.Api/appsettings.json
        connectionString: ${{ secrets.DB_CONNECTION_STRING }} 
    - name: Build the Docker image
      working-directory: .
      run: docker build . -t jameschastain1337/container-name:latest
    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: jameschastain1337
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the images to Docker Hub
      run: docker push jameschastain1337/kittypics
      
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 7.*
        
    - name: Publish .NET Core Project
      run: dotnet publish ./KittyPics_BlazorWASM/KittyPics_BlazorWASM.csproj -c Release -o release

    # changes the base-tag in index.html from '/' to 'KittyPics_BlazorWASM' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to KittyPics_BlazorWASM
      run: sed -i 's/<base href="\/" \/>/<base href="\/kittypics_blazorwasm\/" \/>/g' release/wwwroot/index.html

    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
